name: CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn'

      - run: yarn
      - run: yarn lint
      - run: (cd apps/vscode && npx vsce package --yarn)
      - uses: actions/upload-artifact@v2
        with:
          name: VSCode Preview VSIX
          path: 'apps/vscode/*.vsix'
  
  generate-status-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn'
      - run: yarn
      - run: yarn translation-status
    
